# EKS cluster service file, for accessing

apiVersion: v1
kind: Service
metadata:
  name: project-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: project-demo
